theme: jekyll-theme-cayman
title: Marc'Aurelio Ranzato

# List of links in the navigation bar
navbar-links:
  Publications: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "img/mr.jpg"

author:
  name: Marc'Aurelio Ranzato

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "ranzato@fb.com"
  facebook: marcaurelio.ranzato
  github: ranzato

